[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "toolchain/solc-0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
via_ir = true
offline = true
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"

[profile.default.fuzz]
runs = 512
max_test_rejects = 131_072

[profile.default.invariant]
runs = 256
depth = 500
fail_on_revert = false
dictionary_weight = 80

[profile.ci.fuzz]
runs = 2_000
max_test_rejects = 262_144

[profile.ci.invariant]
runs = 1_000
depth = 750
fail_on_revert = false
dictionary_weight = 85

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
