[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc = "toolchain/solc-0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
via_ir = true
offline = true
fs_permissions = [{ access = "read-write", path = "./" }]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"
